import { useState, useRef, useCallback, useEffect } from "react";
import { addReport } from "@/lib/reports-store";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import {
  Form, FormControl, FormField, FormItem, FormLabel, FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import {
  Send, CheckCircle, Shield, Copy, Check,
  AlertTriangle, UserX, MessageSquareWarning, FileWarning, HelpCircle,
  ExternalLink, ImagePlus, X, FileImage,
} from "lucide-react";

const REASONS = ["spam", "scam", "harassment", "fake_account", "other"] as const;

const REASON_META: Record<string, { label: string; icon: React.ReactNode; wa: string }> = {
  spam:         { label: "Spam",          icon: <MessageSquareWarning className="w-3.5 h-3.5" />, wa: "Spam Messages" },
  scam:         { label: "Scam / Fraud",  icon: <AlertTriangle className="w-3.5 h-3.5" />, wa: "Fraud or Scam" },
  harassment:   { label: "Harassment",    icon: <UserX className="w-3.5 h-3.5" />, wa: "Harassment" },
  fake_account: { label: "Fake Account",  icon: <FileWarning className="w-3.5 h-3.5" />, wa: "Pretending to Be Someone" },
  other:        { label: "Other",          icon: <HelpCircle className="w-3.5 h-3.5" />, wa: "Other" },
};

const schema = z.object({
  targetNumber: z.string().min(5, "Enter a valid phone number"),
  reason: z.enum(REASONS as unknown as [string, ...string[]], { message: "Please select a reason" }),
  details: z.string().min(10, "Please provide at least 10 characters"),
});
type FormValues = z.infer<typeof schema>;

interface UploadedFile {
  name: string;
  size: number;
  preview: string;
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function buildReportMessage(values: FormValues, files: UploadedFile[]): string {
  const now = new Date();
  const dateStr = now.toISOString().replace("T", " ").slice(0, 19) + " UTC";
  const reasonLabel = REASON_META[values.reason]?.wa ?? values.reason;
  const attachmentLine = files.length > 0
    ? `\n📎 Attachments   : ${files.length} screenshot(s) — ${files.map(f => f.name).join(", ")}`
    : "";
  return `🚨 SPAM WA REPORT
━━━━━━━━━━━━━━━━━━━━
📱 Target Number : ${values.targetNumber}
⚠️  Report Type  : ${reasonLabel}
🕒 Timestamp    : ${dateStr}${attachmentLine}
━━━━━━━━━━━━━━━━━━━━
📋 Details:
${values.details}
━━━━━━━━━━━━━━━━━━━━
📧 Report via WhatsApp:
   support@whatsapp.com
🔗 Official Report Page:
   https://www.whatsapp.com/contact/?lang=en
━━━━━━━━━━━━━━━━━━━━
Generated by SPAM WA REPORT · varnox.team`;
}

export default function Home() {
  const [submitted, setSubmitted] = useState<FormValues | null>(null);
  const [isPending, setIsPending] = useState(false);
  const [copied, setCopied] = useState(false);
  const [uploadedFiles, setUploadedFiles] = useState<UploadedFile[]>([]);
  const [isDragging, setIsDragging] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const base = import.meta.env.BASE_URL.replace(/\/$/, "");

  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    // Backup play in case autoPlay attribute is blocked by browser policy
    const tryPlay = () => video.play().catch(() => {});
    // Fire immediately and also after metadata loads (mobile Safari needs this)
    video.addEventListener("loadedmetadata", tryPlay, { once: true });
    // Resume when switching back to this tab
    const onVisibility = () => { if (document.visibilityState === "visible") tryPlay(); };
    document.addEventListener("visibilitychange", onVisibility);
    return () => {
      document.removeEventListener("visibilitychange", onVisibility);
    };
  }, []);

  const form = useForm<FormValues>({
    resolver: zodResolver(schema),
    defaultValues: { targetNumber: "", reason: undefined, details: "" },
  });

  function onSubmit(values: FormValues) {
    setIsPending(true);
    setTimeout(() => {
      addReport(values.targetNumber, values.reason);
      setIsPending(false);
      setSubmitted(values);
    }, 1200);
  }

  function handleCopy(text: string) {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2200);
    });
  }

  const processFiles = useCallback((rawFiles: FileList | null) => {
    if (!rawFiles) return;
    const allowed = Array.from(rawFiles).filter(f => f.type.startsWith("image/")).slice(0, 5);
    allowed.forEach(file => {
      const reader = new FileReader();
      reader.onload = (e) => {
        setUploadedFiles(prev => {
          if (prev.length >= 5) return prev;
          if (prev.find(p => p.name === file.name && p.size === file.size)) return prev;
          return [...prev, {
            name: file.name,
            size: file.size,
            preview: e.target?.result as string,
          }];
        });
      };
      reader.readAsDataURL(file);
    });
  }, []);

  function removeFile(idx: number) {
    setUploadedFiles(prev => prev.filter((_, i) => i !== idx));
  }

  function onDragOver(e: React.DragEvent) {
    e.preventDefault();
    setIsDragging(true);
  }
  function onDragLeave() { setIsDragging(false); }
  function onDrop(e: React.DragEvent) {
    e.preventDefault();
    setIsDragging(false);
    processFiles(e.dataTransfer.files);
  }

  const reportMsg = submitted ? buildReportMessage(submitted, uploadedFiles) : "";

  return (
    <div className="min-h-screen flex flex-col items-center justify-start pt-12 pb-12 px-4">

      {/* ── Hero ───────────────────────────────────────────────── */}
      <div className="text-center mb-10 fade-up">
        <div
          className="inline-flex items-center gap-2 px-3 py-1 rounded-full mb-5 text-xs font-semibold uppercase tracking-widest"
          style={{
            background: "hsl(263 70% 60% / 0.1)",
            border: "1px solid hsl(263 70% 60% / 0.28)",
            color: "hsl(263 70% 75%)",
          }}
        >
          <Shield className="w-3.5 h-3.5" />
          Secure Platform
        </div>
        <h1
          className="gradient-title text-5xl md:text-6xl font-extrabold tracking-tight mb-3 leading-none"
          data-testid="text-page-title"
        >
          SPAM WA REPORT
        </h1>
        <p className="text-sm md:text-base font-light max-w-sm mx-auto leading-relaxed"
          style={{ color: "hsl(var(--muted-foreground))" }}>
          Report suspicious WhatsApp activity safely and efficiently
        </p>
      </div>

      {/* ── Video card ─────────────────────────────────────────── */}
      <div
        className="video-card fade-up w-full max-w-lg mb-10"
        style={{ aspectRatio: "16/7", animationDelay: "100ms" }}
        data-testid="video-card"
      >
        <video
          ref={videoRef}
          autoPlay
          muted
          loop
          playsInline
          preload="auto"
          className="w-full h-full object-cover rounded-[inherit]"
          poster={`${base}/opengraph.jpg`}
          onError={(e) => {
            const el = e.currentTarget;
            el.style.display = "none";
            const parent = el.parentElement;
            if (parent && !parent.querySelector(".vid-fallback")) {
              const fb = document.createElement("img");
              fb.className = "vid-fallback w-full h-full object-cover";
              fb.src = `${base}/opengraph.jpg`;
              fb.alt = "SPAM WA REPORT";
              (fb as HTMLImageElement).style.borderRadius = "inherit";
              parent.appendChild(fb);
            }
          }}
        >
          <source src={`${base}/report-video.mp4`} type="video/mp4" />
          <img src={`${base}/opengraph.jpg`} alt="SPAM WA REPORT"
            className="w-full h-full object-cover" style={{ borderRadius: "inherit" }} />
        </video>
      </div>

      {/* ── Form / Success card ────────────────────────────────── */}
      <div
        className="form-card fade-up w-full max-w-lg p-7"
        style={{ animationDelay: "180ms" }}
      >
        {!submitted ? (
          <>
            <div className="mb-6">
              <h2 className="text-white text-lg font-bold mb-1">Submit a Report</h2>
              <p className="text-xs font-light" style={{ color: "hsl(var(--muted-foreground))" }}>
                Fill in the details — a ready-to-send report message will be generated instantly.
              </p>
            </div>

            <Form {...form}>
              <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-5">

                {/* Target Number */}
                <FormField control={form.control} name="targetNumber" render={({ field }) => (
                  <FormItem>
                    <FormLabel className="text-xs font-bold uppercase tracking-widest"
                      style={{ color: "hsl(var(--foreground))" }}>
                      Target Number
                    </FormLabel>
                    <FormControl>
                      <Input
                        data-testid="input-target-number"
                        placeholder="+224 669 28 83 32"
                        {...field}
                        className="field-input h-11 font-mono"
                      />
                    </FormControl>
                    <FormMessage className="text-xs" />
                  </FormItem>
                )} />

                {/* Reason */}
                <FormField control={form.control} name="reason" render={({ field }) => (
                  <FormItem>
                    <FormLabel className="text-xs font-bold uppercase tracking-widest"
                      style={{ color: "hsl(var(--foreground))" }}>
                      Reason
                    </FormLabel>
                    <Select onValueChange={field.onChange} defaultValue={field.value}>
                      <FormControl>
                        <SelectTrigger data-testid="select-reason" className="field-input h-11">
                          <SelectValue placeholder="Select a reason..." />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent style={{
                        background: "hsl(265 35% 9%)",
                        border: "1px solid hsl(265 25% 18%)",
                      }}>
                        {REASONS.map((r) => (
                          <SelectItem key={r} value={r}
                            className="text-sm focus:bg-[hsl(263,70%,60%,0.12)] focus:text-white"
                            style={{ color: "hsl(var(--foreground))" }}
                            data-testid={`option-reason-${r}`}>
                            <span className="flex items-center gap-2">
                              {REASON_META[r].icon}
                              {REASON_META[r].label}
                            </span>
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage className="text-xs" />
                  </FormItem>
                )} />

                {/* Details */}
                <FormField control={form.control} name="details" render={({ field }) => (
                  <FormItem>
                    <FormLabel className="text-xs font-bold uppercase tracking-widest"
                      style={{ color: "hsl(var(--foreground))" }}>
                      Details
                    </FormLabel>
                    <FormControl>
                      <Textarea
                        data-testid="input-details"
                        placeholder="Describe what this account did — include dates, messages received, links sent, or any other relevant information..."
                        {...field}
                        className="field-input min-h-[110px] resize-none text-sm font-light leading-relaxed"
                      />
                    </FormControl>
                    <FormMessage className="text-xs" />
                  </FormItem>
                )} />

                {/* ── Screenshot Upload ──────────────────────────── */}
                <div>
                  <p className="text-xs font-bold uppercase tracking-widest mb-2"
                    style={{ color: "hsl(var(--foreground))" }}>
                    Screenshots <span className="font-normal normal-case tracking-normal opacity-50">(optional · max 5)</span>
                  </p>

                  {/* Drop zone */}
                  <div
                    onClick={() => fileInputRef.current?.click()}
                    onDragOver={onDragOver}
                    onDragLeave={onDragLeave}
                    onDrop={onDrop}
                    className="cursor-pointer rounded-xl flex flex-col items-center justify-center gap-2 py-6 transition-all"
                    style={{
                      border: `1.5px dashed ${isDragging ? "hsl(263 70% 60% / 0.7)" : "hsl(265 25% 22%)"}`,
                      background: isDragging ? "hsl(263 70% 60% / 0.06)" : "hsl(265 35% 7%)",
                    }}
                  >
                    <div
                      className="w-10 h-10 rounded-full flex items-center justify-center"
                      style={{
                        background: "hsl(263 70% 60% / 0.12)",
                        border: "1px solid hsl(263 70% 60% / 0.25)",
                      }}
                    >
                      <ImagePlus className="w-4.5 h-4.5" style={{ color: "hsl(263 70% 72%)" }} />
                    </div>
                    <div className="text-center">
                      <p className="text-xs font-semibold" style={{ color: "hsl(263 70% 75%)" }}>
                        Click to choose from gallery
                      </p>
                      <p className="text-[11px] mt-0.5" style={{ color: "hsl(var(--muted-foreground))" }}>
                        or drag & drop · PNG, JPG, WEBP
                      </p>
                    </div>
                  </div>

                  {/* Hidden file input */}
                  <input
                    ref={fileInputRef}
                    type="file"
                    accept="image/*"
                    multiple
                    className="hidden"
                    onChange={(e) => processFiles(e.target.files)}
                  />

                  {/* Thumbnails */}
                  {uploadedFiles.length > 0 && (
                    <div className="mt-3 grid grid-cols-3 gap-2">
                      {uploadedFiles.map((f, i) => (
                        <div
                          key={i}
                          className="relative rounded-lg overflow-hidden group"
                          style={{
                            aspectRatio: "1",
                            border: "1px solid hsl(265 25% 18%)",
                            background: "hsl(265 35% 7%)",
                          }}
                        >
                          <img
                            src={f.preview}
                            alt={f.name}
                            className="w-full h-full object-cover"
                          />
                          {/* Overlay on hover */}
                          <div
                            className="absolute inset-0 flex flex-col items-center justify-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity"
                            style={{ background: "hsl(265 35% 5% / 0.85)" }}
                          >
                            <FileImage className="w-4 h-4" style={{ color: "hsl(263 70% 72%)" }} />
                            <span className="text-[10px] text-center px-1 leading-tight"
                              style={{ color: "hsl(265 15% 75%)" }}>
                              {formatBytes(f.size)}
                            </span>
                          </div>
                          {/* Remove button */}
                          <button
                            type="button"
                            onClick={(e) => { e.stopPropagation(); removeFile(i); }}
                            className="absolute top-1 right-1 w-5 h-5 rounded-full flex items-center justify-center transition-opacity"
                            style={{
                              background: "hsl(0 65% 50% / 0.85)",
                              border: "1px solid hsl(0 65% 60% / 0.4)",
                            }}
                          >
                            <X className="w-2.5 h-2.5 text-white" />
                          </button>
                        </div>
                      ))}

                      {/* Add more slot if < 5 */}
                      {uploadedFiles.length < 5 && (
                        <button
                          type="button"
                          onClick={() => fileInputRef.current?.click()}
                          className="rounded-lg flex items-center justify-center transition-all"
                          style={{
                            aspectRatio: "1",
                            border: "1.5px dashed hsl(265 25% 22%)",
                            background: "hsl(265 35% 7%)",
                            color: "hsl(265 15% 50%)",
                          }}
                        >
                          <ImagePlus className="w-5 h-5" />
                        </button>
                      )}
                    </div>
                  )}
                </div>

                <Button
                  type="submit"
                  data-testid="button-send-report"
                  className="send-btn w-full h-12 text-white flex items-center justify-center gap-2.5 mt-1 font-semibold tracking-wide"
                  disabled={isPending}
                >
                  {isPending ? (
                    <>
                      <div className="w-4 h-4 rounded-full border-2 border-white/30 border-t-white animate-spin" />
                      Generating report...
                    </>
                  ) : (
                    <>
                      <Send className="w-4 h-4" />
                      Generate Report
                    </>
                  )}
                </Button>
              </form>
            </Form>
          </>
        ) : (
          /* ── Success + Report message ──────────────────────── */
          <div className="space-y-5 fade-up" data-testid="success-state">
            {/* Success header */}
            <div className="flex items-center gap-3">
              <div
                className="w-10 h-10 rounded-full flex items-center justify-center shrink-0"
                style={{
                  background: "hsl(142 60% 45% / 0.12)",
                  border: "1.5px solid hsl(142 60% 45% / 0.35)",
                }}
              >
                <CheckCircle className="w-5 h-5 text-green-400" />
              </div>
              <div>
                <p className="text-green-400 font-bold text-base">Report Generated!</p>
                <p className="text-xs font-light" style={{ color: "hsl(var(--muted-foreground))" }}>
                  Copy the message below and send it to WhatsApp support
                </p>
              </div>
            </div>

            {/* Screenshots preview */}
            {uploadedFiles.length > 0 && (
              <div>
                <p className="text-xs font-bold uppercase tracking-widest mb-2"
                  style={{ color: "hsl(263 70% 72%)" }}>
                  Attached Screenshots ({uploadedFiles.length})
                </p>
                <div className="flex gap-2 flex-wrap">
                  {uploadedFiles.map((f, i) => (
                    <div
                      key={i}
                      className="rounded-lg overflow-hidden"
                      style={{
                        width: 60, height: 60,
                        border: "1px solid hsl(265 25% 18%)",
                      }}
                    >
                      <img src={f.preview} alt={f.name} className="w-full h-full object-cover" />
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Generated message */}
            <div
              className="rounded-xl p-4 relative"
              style={{
                background: "hsl(265 50% 5%)",
                border: "1px solid hsl(265 25% 18%)",
              }}
            >
              <pre className="text-xs leading-relaxed whitespace-pre-wrap font-mono"
                style={{ color: "hsl(265 15% 80%)" }}>
                {reportMsg}
              </pre>
              <button
                onClick={() => handleCopy(reportMsg)}
                className="absolute top-3 right-3 flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-semibold transition-all"
                style={{
                  background: copied ? "hsl(142 60% 45% / 0.2)" : "hsl(263 70% 60% / 0.18)",
                  border: `1px solid ${copied ? "hsl(142 60% 45% / 0.4)" : "hsl(263 70% 60% / 0.35)"}`,
                  color: copied ? "hsl(142 60% 65%)" : "hsl(263 70% 80%)",
                }}
              >
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                {copied ? "Copied!" : "Copy"}
              </button>
            </div>

            {/* How to report */}
            <div
              className="rounded-xl p-4 space-y-3"
              style={{
                background: "hsl(263 70% 60% / 0.06)",
                border: "1px solid hsl(263 70% 60% / 0.18)",
              }}
            >
              <p className="text-xs font-bold uppercase tracking-widest" style={{ color: "hsl(263 70% 72%)" }}>
                Send your report officially
              </p>
              <div className="space-y-2">
                {[
                  {
                    label: "Email WhatsApp Support",
                    href: `mailto:support@whatsapp.com?subject=Spam%20Report%20${encodeURIComponent(submitted.targetNumber)}&body=${encodeURIComponent(reportMsg)}`,
                    icon: "📧",
                  },
                  {
                    label: "WhatsApp Official Report Page",
                    href: "https://www.whatsapp.com/contact/?lang=en",
                    icon: "🌐",
                  },
                  {
                    label: "Report inside WhatsApp app",
                    href: `https://api.whatsapp.com/send?phone=${submitted.targetNumber.replace(/\D/g, "")}`,
                    icon: "📱",
                  },
                ].map((link) => (
                  <a
                    key={link.href}
                    href={link.href}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center gap-2.5 text-xs font-medium transition-colors hover:text-white group"
                    style={{ color: "hsl(265 15% 70%)" }}
                  >
                    <span>{link.icon}</span>
                    <span className="flex-1">{link.label}</span>
                    <ExternalLink className="w-3 h-3 opacity-0 group-hover:opacity-100 transition-opacity" />
                  </a>
                ))}
              </div>
            </div>

            <button
              onClick={() => { setSubmitted(null); setCopied(false); setUploadedFiles([]); }}
              className="w-full text-sm font-semibold py-3 rounded-xl transition-all hover:text-white"
              style={{ color: "hsl(263 70% 72%)" }}
              data-testid="button-report-another"
            >
              ← Submit another report
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
